services:
  db:
    image: postgres:16
    container_name: resto-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resto
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: resto-adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
